uktrade/stream-read-xbrl

test_stream_read_xbrl.py

This reverts commit 127f5a16360ec981ca6f5f36b5a3a0e8b1d57f79.
The test_stream_read_xbrl_daily_all will take far too long without the break

revert: "tests: avoid HTTP error during tests due to ending request early"

---

stream_read_xbrl.py

Slightly unfortunately there isn't a test for this

fix: use correct parser when a list

---

stream_read_xbrl.py

There was an attempt to re-use the process pool for multiple zip files. It's simpler to not, and it fixes errors relating to the pool not running as files are processed.

fix: pool-related errors when running stream_read_xbrl_daily_all

---

stream_read_xbrl.py

At least when running locally there can be timeouts. Suspect that the httpx defaults are too short in this case.

feat: increase HTTP-related timeouts from 5s to 60s

---

pyproject.toml
stream_read_xbrl.py
test_stream_read_xbrl.py

Note that the boto3 cient is a dev dependency, not a regular dependency. This is deliberate to keep the dependencies of this library down, especially for non-core behaviour that all users wouldn't use.
While it's a bit old-school, CSVs are quite streaming-friendly and widely supported. A downside is that there is no distinction between the empty sting and a null value, but for many use-cases this is acceptable.

feat: sync parsed data to S3 as CSV files

---

docs/investigating-data.md

The config for this documentation was added in
7de9bb0a7f3c0216dfc2e991e5e7bc19d61b03ab, but not the documentation itself

docs: add brief Investigating data documentation

---

docs/assets/dit-extra.css
mkdocs.yml
requirements-docs.txt

This includes removing CSS. The equivalent CSS has been incorporated into this version of mkdocs-tech-docs-template

build(deps): bump mkdocs-tech-docs-template

---

pyproject.toml
stream_read_xbrl.py
test_stream_read_xbrl.py

If the name was in a <span> element, it wouldn't be found. Instead, it would actually choose the last <span> element in the document, which would be completely unrelated text - often a page number.

fix: entity_current_legal_name

---

stream_read_xbrl.py

A file was published that had this name:
http://download.companieshouse.gov.uk/Accounts_Monthly_Data-od22.zip
But it seems to be identical to this file:
http://download.companieshouse.gov.uk/Accounts_Monthly_Data-December2022.zip
So skipping the "od22" one - our best guess is that it was incorrectly published.

fix: skip files that seem incorrectly published

---

stream_read_xbrl.py

Previous logic ensured no overlaps in start and end dates for files to reduce duplication, but this may have been preventing some daily files from being ingested as a large amount of data was missing, so this has been removed. We will instead look to deal with the duplication later.

fix: removed logic for overlapping dates

---

stream_read_xbrl.py
test_stream_read_xbrl.py

This is to avoid missing files, for example a monthly file and a daily file on the last day of the month.
It's not guaranteed that a montly file is exactly all of its daily files, so we have to ingest all of them and then put the onus on client code to deduplicate.

feat: save both start and end date when syncing to S3

---

stream_read_xbrl.py
test_stream_read_xbrl.py

It was found that balance_sheet_date can contain nested elements, and the date is in those elements. Interestingly, this was one of the existing test cases. However, in the real data, examples were found where the year was split across tags, so a test is added to handle that case.

feat: combine text of all child elements to handle split balance sheet dates

---

stream_read_xbrl.py
test_stream_read_xbrl.py

But that still have the correct first 3 characters

feat: parse dates with incorrect spellings of months

---

stream_read_xbrl.py
test_stream_read_xbrl.py

Some dates in xbrl tags include suffixes, for example "31st March" This was then creating errors when we parsed dates that could be misspelled by checking the first 3 letters of the month. This PR should address this issue by removing the suffixes.

fix: parse dates with suffixes

---

stream_read_xbrl.py
test_stream_read_xbrl.py

In order to deal with many different date formats, we strip the date suffixes e.g. "st" in 31st. However, this was previously case sensitive and so would not strip the suffix if capitalised.

fix: case insensitive date suffix removal

---

stream_read_xbrl.py
test_stream_read_xbrl.py

In order to deal with the variety of exceptions thrown by the Companies House Accounts pipeline, this PR adds an error column which is populated by the error if a ValueError is thrown, allowing the pipeline to continue running.

feat: add error column and populate

---

.github/workflows/tests.yml
codecov.yml
pyproject.toml
stream_read_xbrl.py

The ProcessPoolExecutor from concurrent.futures doesn't need a hack from running from a daemon for Python 3.8 onwards, at least according to https://stackoverflow.com/a/61470465/1319998.
Suspect this also works better with code coverage, so a nice bonus.

feat: remove hack for running process from a daemon, and remove support for Python 3.7

---

stream_read_xbrl.py

At the moment https://download.companieshouse.gov.uk/ seems to have a certificate that isn't recongised by certain tools, e.g. httpx. So for now, suspect a custom httpx client needs to be passed into methods with a customised `verify` argument, and this client actually needs to be used.

fix: use passed in httpx client

---

stream_read_xbrl.py
test_stream_read_xbrl.py

This is to work around the behaviour of the Companies House Accounts server terminating connections that have been open a long time. If we request less data at a time, this is less likely to happen.

feat: range request chunking to work around slow connections getting closed

---

stream_read_xbrl.py
test_stream_read_xbrl.py

September's accounts includes at least one file in the numdotcomma format, so this has to be supported too

fix: support additional decimal format

---

stream_read_xbrl.py
test_stream_read_xbrl.py

To fix the issue detailed: https://github.com/uktrade/stream-read-xbrl/issues/183
Some reports had multiple values for a single cell. In this instance the values are now summed in the _parse_decimal function. 
An appropriate unit test has been added to account for this.

Add logic to sum multiple total values in _parse_decimal with appropriate unit test

---

pyproject.toml

Some tests fail on v8. Not sure why at this point, but pinning to a version before 8 fixes tests.

build(deps): pin pytest to before 8
